// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx68b1c7e6x7ive0httWjE9jPkP4yfsTE',
    appId: '1:1062789909228:web:5f12d26cafd53e266173c9',
    messagingSenderId: '1062789909228',
    projectId: 'flutterapalah',
    authDomain: 'flutterapalah.firebaseapp.com',
    storageBucket: 'flutterapalah.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWc65prV9SaaAkVoOyu1087gylJdIhXSE',
    appId: '1:1062789909228:android:c0442c291d4e05356173c9',
    messagingSenderId: '1062789909228',
    projectId: 'flutterapalah',
    storageBucket: 'flutterapalah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeUuKnX8UaXY4MV96P9TZ9k6X7d9X7NCo',
    appId: '1:1062789909228:ios:9093267b72a159066173c9',
    messagingSenderId: '1062789909228',
    projectId: 'flutterapalah',
    storageBucket: 'flutterapalah.appspot.com',
    iosBundleId: 'com.example.flutterbase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeUuKnX8UaXY4MV96P9TZ9k6X7d9X7NCo',
    appId: '1:1062789909228:ios:9093267b72a159066173c9',
    messagingSenderId: '1062789909228',
    projectId: 'flutterapalah',
    storageBucket: 'flutterapalah.appspot.com',
    iosBundleId: 'com.example.flutterbase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx68b1c7e6x7ive0httWjE9jPkP4yfsTE',
    appId: '1:1062789909228:web:787b8a510da72b446173c9',
    messagingSenderId: '1062789909228',
    projectId: 'flutterapalah',
    authDomain: 'flutterapalah.firebaseapp.com',
    storageBucket: 'flutterapalah.appspot.com',
  );
}
